MODEL_NAME = "Qwen/Qwen3-1.7B"
TRAIN_FILE = "..."
OUTPUT_DIR = "output/lora_sft"

ENTITY_TYPES = ["name", "company"]

MAX_LENGTH = 512

LORA_R = 8
LORA_ALPHA = 16
LORA_DROPOUT = 0.05

BATCH_SIZE = 2
GRAD_ACCUM_STEPS = 4
NUM_EPOCHS = 3
LEARNING_RATE = 2e-4
LOGGING_STEPS = 10
SAVE_STEPS = 100